language: c

matrix:
  include:
    - compiler: clang
    - env:
      - secure: "H+FS0KWYGx4JBMcPdhhJus9LgFhh5luIU4rfWl6Fsh4q0VJmT1tSO3KYlEQYkenS4xX/sUtN/Yus1b8L0MkuM3akEEPAA26Up9leFsarIQrD3dGYmoNQ4R2eG1Et8hoNwQwXQ1f30wrqfykVK+83rzqSlpoz+nhTBKZNYC7tfn0="
      compiler: gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq puredata-dev

script:
- make

addons:
  coverity_scan:
    project:
      name: umlaeute/pd-iemnet
    notification_email: zmoelnig@users.sourceforge.net
    build_command: make
    branch_pattern: coverity_scan
